name: Staff Sorcery
favicon: null
layout_spectrum: 0.28687
typography_spectrum: 0.32794
title: 'R&D for Wirral Recruitment '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0dbbb5'
    - '#064b73'
    - '#000000'
    - '#00ffff'
    - '#008080'
  brandStrength: 0.1875
  lightness: 0.6771545808296651
  saturation: 0.5
  rhythmicContrast: 0.02823299402371049
purpose: []
